{{- if .Values.sealedsecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: {{ template "chart.fullname" . }}-sealedsecret
spec:
  encryptedData:
    {{ .Values.sealedsecret.filename }}: |-
      {{ .Values.sealedsecret.config | nindent 4 | trim }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app: {{ .Values.appName }}
      name: {{ template "chart.fullname" . }}-sealedsecret
{{- end }}
